<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <GenerateProgramFile>false</GenerateProgramFile>
    <AssemblyName>Operations.Research.Test</AssemblyName>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../or/or.fsproj">
      <Name>or.fsproj</Name>
    </ProjectReference>
  </ItemGroup>
  <ItemGroup>
    <Compile Include="types.fs" />
    <Compile Include="model.fs" />
    <Compile Include="solvers/google.linear.fs" />
    <Compile Include="solvers/google.constraint.fs" />
    <Compile Include="solvers/google.route.fs" />
    <Compile Include="examples.fs" />
    <Compile Include="program.fs" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="../lib/TestTracks-1.2.0/TestTracks.dll" />
  </ItemGroup>
  
</Project>
