name: Operations Research CI/CD

on:
  push:
    branches:
      - "**"
    tags:
      - v*

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install Task Runner
        run: dotnet fsi tools/install-task-runner.fsx

      - name: Run Tests
        run: ./tools/tusk test

  build-release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runtime: [linux-x64, win-x64, osx-x64, osx-arm64]
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install Task Runner
        run: dotnet fsi tools/install-task-runner.fsx

      - name: Clean
        run: ./tools/tusk clean

      - name: Build Release
        run: |
          RELEASE_VERSION=$(git describe --abbrev=0 --tags)
          VERSION_NUM=$(echo $RELEASE_VERSION | cut -c 2-)
          ./tools/tusk release -version=$VERSION_NUM -runtime=${{ matrix.runtime }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: operations-research-${{ matrix.runtime }}
          path: operations-research-*.tar.gz
          retention-days: 64

  create-release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build-release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          RELEASE_VERSION=$(git describe --abbrev=0 --tags)
          gh release create $RELEASE_VERSION \
            --title "Release $RELEASE_VERSION" \
            --draft \
            --generate-notes \
            artifacts/**/*.tar.gz
