name: Operations Research New Feature

on:
  push:
    branches-ignore:
      - master

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.103
    - name: Install Task Runner
      run: ./tools/install-task-runner.sh
    - name: Clean
      run: ./tools/tusk clean
    - name: Run Tests
      run: ./tools/tusk test
