name: Operations Research

on:
  push:
    branches:
      - master

jobs:
  build-test-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Install Task Runner
      run: ./tools/install-task-runner.sh
    - name: Clean
      run: ./tools/tusk clean
    - name: Run Tests
      run: ./tools/tusk test
    - name: Build Package
      run: ./tools/tusk release
      env:
        RELEASE_VERSION: ${{ secrets.RELEASE_VERSION }}
    - name: Publish to 'nuget.org'
      run: ./tools/tusk publish --apiKey=${{ secrets.NUGET_API }}
